apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: dev
build:
  insecureRegistries:
    - 127.0.0.1:5000
  artifacts:
  - image: authentication-service
    context: ./authentication-service/
  - image: profile-service
    context: ./profile-service/
  - image: edge
    context: ./edge/
deploy:
  kubectl:
    manifests:
    - kubernetes/*
    - authentication-service/kubernetes/dev*
    - profile-service/kubernetes/dev*
    - edge/kubernetes/dev*
