apiVersion: v1
kind: Service
metadata:
  name: neo4j-public
  labels:
    app: neo4j
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    name: discovery
  - port: 7000
    targetPort: 7000
    name: raft
  - port: 6000
    targetPort: 6000
    name: tx
  - port: 7474
    targetPort: 7474
    name: browser
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: neo4j